### ISSUE TITLE
[優先度低]トップページLatest blocks,Txsにスクロールバーを実装

### ISSUE THREAD

**Issue by Senna46** [lcnem/cosmoscan#108]
今のままだとLatest blocks,Txsが20件ずつ表示されるため、ページが長くなっている
Etherscanのようにスクロールバーを実装するUIの更新を実施予定。

**Comment by KimuraYu45z** [comment]
htmlでdivで囲い、
そのdivに対してcssでoverflow: autoとheight定数指定

**Comment by Senna46** [comment]
APIの実装が終わったらやる予定ですが参考にするのはこのあたりでしょうか？
https://developer.mozilla.org/ja/docs/Learn/CSS/Building_blocks/Overflowing_content

**Comment by KimuraYu45z** [comment]
そうですね。
