### ISSUE TITLE
[優先度低]トップページLatest Txsの並びを逆にする

### ISSUE THREAD

**Issue by Senna46** [lcnem/cosmoscan#112]
Websocket有効化後、関連箇所のコメントアウトを外す際に実施予定。

**Comment by Senna46** [comment]
wsでの取得と配列の成形
`projects/cosmoscan/src/app/home/txs/txs.component.ts`

表示
`projects/cosmoscan/src/view/txs/tx/tx.component.html`

**Comment by Tomosuke0930** [comment]
@Senna46 さん
現状のご報告をさせていただきます。

下記のようなコードに変更することで順番を逆にすることはできました。
Before
`<ng-container *ngFor="let initialTx of initialTxs">`
After
`<ng-container *ngFor="let initialTx of initialTxs!.slice().reverse()">`
![Uploading スクリーンショット 2021-09-07 14.40.45.png…]()

ただコミットしようとすると下記のようなエラーが出てしまい詰まっている状況です。
調べてみると記事が出てきたのですが時間がかかりそうですが取り掛かってみます。
`Git: .husky/commit-msg: line 4: npx: command not found`

**Comment by Senna46** [comment]
huskyの再インストールで治らないですか？
`npm i husky`

**Comment by KimuraYu45z** [comment]
`npx husky init`も

**Comment by Tomosuke0930** [comment]
@KimuraYu45z @Senna46 
試してみたのですが下記のようなエラーが出てしまいました。

```
(base) tom@mba cosmoscan % npm i husky       

up to date, audited 2433 packages in 28s
~
省略
~
Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.


(base) tom@mba cosmoscan % npx husky init
husky - updated package.json
husky - Git hooks installed
husky - created .husky/pre-commit


(base) tom@mba cosmoscan % git commit -m "fix:initialTxs-array"

> cosmoscan@0.0.0 test
> npx jest

 PASS  projects/cosmoscan/src/app/app.component.spec.ts
  test
    ✓ dummy (1 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.325 s
Ran all test suites.
⧗   input: fix:initialTxs-array
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]

✖   found 2 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint

husky - commit-msg hook exited with code 1 (error)
```

**Comment by KimuraYu45z** [comment]
`git commit -m "fix: initialTxs-array"`

スペース要りますね

**Comment by KimuraYu45z** [comment]
`feat: `か`chore: `か`fix: `とかだけ覚えとけばいいです

**Comment by KimuraYu45z** [comment]
あとハイフンとかlowerCamelCase、UpperCamelCaseな文字列もダメなことがおおいです小文字スペースで
