### ISSUE TITLE
Public key,AdressのPrefixがjpyxになっていない

### ISSUE THREAD

**Issue by Senna46** [lcnem/cosmoscan#27]
Cosmoscanでmnemonicを渡して生成されるPublic key、AccAdressのPrefixにjpyxが入っておらず、VPSのmainのアドレスと一致しない。
Cosmosで生成されたもの
`Public Key 02f49fd94fc1db75192af2d30f4138c6a277dcd9f4679e769d70a493011f95e8ae`
`AccAddress cosmos10lcj22kzftvnduchatmnsnhfljeky5gh2nph3h`

VPSのmain
`pubkey: jpyxpub1addwnpepqt6flk20c8dh2xf27tfs7sfcc6380hxe73neua5awzjfxqgljh52urfdzmf`
`address: jpyx10lcj22kzftvnduchatmnsnhfljeky5ghd398wt`

**Comment by KimuraYu45z** [comment]
`projects/cosmoscan-extension/editions/jpyx/config-jpyx.json`

ここが該当箇所。

**Comment by Senna46** [comment]
本件、無事解決しました。
BotanyのDockerfileの変更漏れが原因でした。
`COPY ./botany/projects/cosmoscan-extension/editions/jpyx/config-jpyx.json`
