### ISSUE TITLE
Docker Hubのイメージビルド結果のSlack通知設定

### ISSUE THREAD

**Issue by YasunoriMATSUOKA** [lcnem/cosmoscan#35]
以下の公式ドキュメントを参考にDocker HubのWeb上の管理画面から設定できる見込み
https://docs.docker.com/docker-hub/slack_integration/

**Comment by KimuraYu45z** [comment]
これって、docker imageのビルドをgithub actions化したら、意味なくなる感じでしょうか？

**Comment by YasunoriMATSUOKA** [comment]
あ、確かにそうかもしれません...
こちらの設定を加えた上で、GitHub Actions化して通知飛ぶかどうか試してみますね...
(Docker Hub上でイメージをビルドした場合の結果がSlack通知されるだけだと通知飛ばないかもですね...)

**Comment by KimuraYu45z** [comment]
試す以前に絶対飛ばない気がしますｗ
(docker hubにpushされた通知ならactionsからbuildとpushしても飛ぶと思いますが、docker hubのbuildはgithubと一切関係がないためdocker hubのbuildの通知設定も同様

**Comment by YasunoriMATSUOKA** [comment]
承知しました。こちらクローズしておきましょうか？

**Comment by KimuraYu45z** [comment]
github actions化したほうが結果も見やすいしslack通知も簡単に作れるので、一本化するということにして(ただしそんな優先度は高くなくていい)、これはcloseしましょう！
