### ISSUE TITLE
DockerイメージのビルドとDocker HubへのプッシュをGitHub Actions化

### ISSUE THREAD

**Issue by YasunoriMATSUOKA** [lcnem/cosmoscan#36]
以下を設定する必要があるという認識
https://docs.github.com/ja/actions/guides/publishing-docker-images

プッシュする際、コンテナイメージのタグにGitHubでrelease作成時のタグ名を含めたいので、それらの設定は以下を参考に$GITHUB_REFを使ってGitHub Actionsを実装する
https://docs.github.com/ja/actions/reference/environment-variables#default-environment-variables

**Comment by KimuraYu45z** [comment]
優先度は低～中くらいの認識でお願いします！

**Comment by KimuraYu45z** [comment]
(m1 でのbuildがめんどくさいのが連続する場合は優先度上げていいです！

**Comment by KimuraYu45z** [comment]
- jpyx
- eurx
- cosmoscan
- botany

これらのリポジトリで

```
${{ secrets.DOCKER_USERNAME }}
${{ secrets.DOCKER_PASSWORD }}
```

こいつらだけ設定しておきますね。

**Comment by YasunoriMATSUOKA** [comment]
m1で完結せず、Windows機といったりきたりする精神的負荷(笑)が結構大きく、優先度高く、今日午前中くらいの気持ちでやっつけてしまいたい気分です...
リリースをトリガーに、以下の二通りでプッシュするようなイメージで考えていて、このIssueの参考リンクのイメージならある程度すぐできそうかなと思っているので、優先度高く早めにやっつけてしまいたいな...と思っています。

```
lcnem/cosmoscan:latest
lcnem/cosmoscan:$GITHUB_REF
```

**Comment by KimuraYu45z** [comment]
了解です！secret設定完了しました！

**Comment by YasunoriMATSUOKA** [comment]
GitHub Actionsで、Docker Hubへのプッシュで、タグ名を`${{ github.ref }}`で指定している箇所が以下のようになっていてエラーで落ちました。
`error: invalid tag "lcnem/cosmoscan:refs/tags/v0.0.1": invalid reference format`
修正のため、Issueリオープンします。

**Comment by KimuraYu45z** [comment]
あー
`github.ref`とってると`v0.0.1`じゃなく`refs/tags/v0.0.1`が入るんですね。

**Comment by YasunoriMATSUOKA** [comment]
Shell芸？でrefs/tags/を消す形で修正を試みました。再度プルリク作成するので、少々お待ちください。

**Comment by KimuraYu45z** [comment]
素晴らしい！

**Comment by YasunoriMATSUOKA** [comment]
Shell芸失敗... 
`error: invalid tag "lcnem/cosmoscan:${refs/tags/v0.0.2//refs\\/tags\\//}": invalid reference format`
${}のつけかたミスっている感じです。
もうちょっと調べてみます。

**Comment by KimuraYu45z** [comment]
${}のなかは環境変数が展開できるだけで、シェル使えるわけじゃないのかもしれないですね。
https://qiita.com/hotpepsi/items/756bf03812af66fdeb8c

**Comment by KimuraYu45z** [comment]
https://scrapbox.io/Sixeight/GItHub_Actions%E3%81%A7%E5%AE%9F%E8%A1%8C%E5%AF%BE%E8%B1%A1%E3%81%AE%E3%82%BF%E3%82%B0%E3%82%92%E5%8F%96%E5%BE%97%E3%81%99%E3%82%8B

**Comment by YasunoriMATSUOKA** [comment]
理解しました！修正試みます！

**Comment by YasunoriMATSUOKA** [comment]
エラーになりましたが、バージョン指定はできているのかな？と思いました。
問題の原因は、バージョンがタグとしてセットされたDockerイメージをGitHub Actions環境内で作っていないにも関わらず、それをDocker Hubにプッシュしようとしているからなのかな？と思いました。

 エラー内容

```
Error: buildx failed with: error: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount731905588/Dockerfile: no such file or directory
```

https://github.com/lcnem/cosmoscan/actions/runs/1003023646

後で詳細確認します。バージョン付きのプッシュが解決に時間かかりそうな場合、一旦バージョンなしのlatestのみのプッシュを実装しておく方向もありかなと思い始めています。

**Comment by KimuraYu45z** [comment]
あーわかった
そもそも
https://github.com/docker/build-push-action

このactionsがbuildも受け持つ形なんですね。だからnpm run bundleがそもそも不要で、逆にactionsにはdocker build contextの位置指定とdockerfile位置指定を入れないといけないですね。

**Comment by KimuraYu45z** [comment]
となるとタグつけは結構面倒そうなので、まずlatestだけで進めちゃいましょう。

**Comment by YasunoriMATSUOKA** [comment]
なるほど、Dockerfileのパスをwith配下のcontextで渡してあげればそこでビルドしてくれる感じなんですね。
npm run bundle関連のところを消して、Dockerfileのパスをwith配下のcontextで記述する形で修正トライしてみます。

**Comment by KimuraYu45z** [comment]
context指定はあるのですがdockerfileの位置指定する方法が見当たらないですね。。。

もしかしたらworking-directoryでdockerfileある位置に行かせて、そこを起点にcontextをリポジトリ直下にいくまで..する、が解かもしれません。

**Comment by KimuraYu45z** [comment]
dockerfileの位置指定はcontextとはまた別の概念で、buildコマンドでは第一引数にcontextをいれていて、-fフラグでdockerfile位置指定しているやつです。

**Comment by YasunoriMATSUOKA** [comment]
ありがとうございます。working-directoryの設定で試してみますね。

**Comment by KimuraYu45z** [comment]
エラー内容はまさしく

```
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount731905588/Dockerfile: no such file or directory
```

Dockerfileが見つかりませんでした、でした。

**Comment by YasunoriMATSUOKA** [comment]
追加で調べたところ、以下URLの記述で、contextとfileの両方を指定すればOKそうな気がしました。
https://github.com/docker/build-push-action#inputs

あるいは、以下も参考になるかもしれず、そのあたりの指定を試してみようと思います。
https://stackoverflow.com/questions/63786311/how-to-set-correct-working-directory-for-docker-building-and-publishing-in-githu

**Comment by KimuraYu45z** [comment]
おお、このstackoverflow完璧ですね！with dockerfileでいけそう。
さらにtag_with_refやっとけばref切り捨てもやってくれそうですね。

**Comment by YasunoriMATSUOKA** [comment]
一旦公式側の方法を試してみて、だめだったらstackoverflow側の記述を試してみようと思います。

**Comment by YasunoriMATSUOKA** [comment]
シンプルなDockerイメージビルド&Docker Hubへのプッシュは公式記載の方法で、stackoverflow記載の内容はGitHub Package特有の書き方なのかもしれないなど思いました。
