### ISSUE TITLE
[優先度中]サイドメニューの未テストの機能のstakingをテストして有効化する

### ISSUE THREAD

**Issue by YasunoriMATSUOKA** [lcnem/cosmoscan#44]

**Comment by YasunoriMATSUOKA** [comment]
先週の打ち合わせで出ていた、アーニングスの表示という点で、stakingの機能が必要になるように感じたので、優先度高に変更します。

**Comment by KimuraYu45z** [comment]
どうだろう、表示(get系)さえできればpost系は後回しでもいいと思います。

**Comment by YasunoriMATSUOKA** [comment]
なるほど、ちょっと自分の中でどんな機能があるか把握できていないので確信が持てていないのですが、一旦、優先度中に戻しておきますね。

**Comment by Senna46** [comment]
有効化は実施済み
残りの作業は #84 にあるのでクローズします
