### ISSUE TITLE
[優先度低]cosmoscanレポジトリの変更をトリガーにしてbotanyレポジトリのGitHub Actionsを動かすことで各レポジトリで個別にGitHub Actionsを手動でトリガーする手間をなくせないか

### ISSUE THREAD

**Issue by YasunoriMATSUOKA** [lcnem/cosmoscan#53]
@KimuraYu45z 
少し調べたところ、以下のような内容が実現でそうに見えています。的外れでなければ、トライしてみようと思うのですが、いかがでしょうか？ご相談させてください。

cosmoscanへ変更が入ったらDockerイメージlcnem/cosmoscan:latestをビルドしてDocker Hubにプッシュし、botanyレポジトリにイベントを通知し、botanyレポジトリではそのイベントをトリガーに起動するGitHub Actionsでlcnem/cosmoscan-jpyxやlcnem/cosmoscan-eurxやlcnem/botany-pricefeedのDockerイメージをビルドしてDocker Hubにプッシュするようにできないか？

以下URLの情報が参考になりそう。
https://qiita.com/horitaka/items/14ac325a26635b391b79

**Comment by KimuraYu45z** [comment]
なるほど！優先度低で、やる価値あると思います！

**Comment by YasunoriMATSUOKA** [comment]
ありがとうございます。どこかでトライしてみようと思います。

**Comment by YasunoriMATSUOKA** [comment]
@Senna46 
プルリク＆リリースして動作検証ありがとうございました。
ただ、変更入れてもらった部分で、GitHub Actionsがエラーになっているようでした。
https://github.com/lcnem/cosmoscan/runs/3054238433?check_suite_focus=true
ざっと見たところ、プルリクで見落としてしまっていて恐縮でしたが、末尾に`'`が抜けているのが原因のように思います。
お手すきの際に修正お願いします。

**Comment by Senna46** [comment]
@YasunoriMATSUOKA botany側でもcosmoscanリリースにトリガーされてActionが動くのを確認しました。
フォロー本当にありがとうございました。
