### ISSUE TITLE
[優先度高]txBuilder.addSignatureで指定すべき引数を変更する必要がある

### ISSUE THREAD

**Issue by YasunoriMATSUOKA** [lcnem/cosmoscan#60]
@KimuraYu45z 
ローカルでng serveしたところ、以下のようなエラーが発生しました。
cosmos-client-tsのバージョンをv0.42.4 -> v0.42.6に上げた際、txBuilder.addSignatureで指定すべき引数を変更する必要があるという状況かと見えています。
お手数ですが、上記コメント違和感ないかどうか確認いただけると助かります。
一旦、こちらで修正試みてみますが、解決に時間がかかりそうであれば、ご相談させてください。

```
Error: projects/cosmoscan/src/model/cosmos/bank.service.ts:62:37 - error TS2554: Expected 1 arguments, but got 2.

62     txBuilder.addSignature(privKey, signDoc);
                                       ~~~~~~~


Error: projects/cosmoscan/src/model/cosmos/staking.service.ts:67:37 - error TS2554: Expected 1 arguments, but got 2.

67     txBuilder.addSignature(privKey, signDoc);
```

**Comment by KimuraYu45z** [comment]
あ、そうでしたそこちょっとバグ対策のために引数変えたんですよね。

https://github.com/cosmos-client/cosmos-client-ts/blob/main/src/rest/cosmos/bank/bank.spec.ts#L60
↑こんな感じになります。

**Comment by YasunoriMATSUOKA** [comment]
@KimuraYu45z 
問題の箇所を以下のように置き換えたところ、

```
    const signDocBytes = txBuilder.signDocBytes(account.account_number);
    txBuilder.addSignature(privKey.sign(signDocBytes));
```

以下のようなエラーが発生しました。

```
Error: projects/cosmoscan/src/model/cosmos/bank.service.ts:58:49 - error TS2345: Argument of type 'Long | null | undefined' is not assignable to parameter of type 'Long'.
  Type 'undefined' is not assignable to type 'Long'.

58     const signDocBytes = txBuilder.signDocBytes(account.account_number);
```

cosmos-client-ts内で定義されているtxBuilder.signDocBytesの引数の型が、Longで定義されているのに対し、Long | null | undefinedな型の引数を指定しているのが問題だと思うのですが、昨夜加えて頂いた修正を考慮すると、ここで引数をLongに加工してはならず、nullならnullのまま、undefinedならnullにする(かあるいはundefinedのまま？)等して渡す必要があるという理解をしています。
したがって、cosmos-client-ts内で定義されているtxBuilder.signDocBytesに相当する関数の引数の型の定義を、Longではなく、Long | null | undefinedに修正し、nullやundefinedの場合も正常に動作するようにcosmos-client-ts側を修正する必要があるという理解をしているのですが正しいでしょうか？

まだ、cosmos-client-ts側をチェックしていないのですが、上記理解が正しく、こちらでも修正可能なレベル感であれば、cosmos-client-ts側の修正をトライしてみようと思います。

上記ご確認の上、こちらでcosmos-client-ts側の修正を行ったほうが良いか？、あるいは木村さんにて修正頂いたほうが良いか？あるいは何か見当違いのことを言っていないか等、アドバイス頂けると助かります。

よろしくお願いします。

**Comment by YasunoriMATSUOKA** [comment]
メモ

上記コメントは、修正方法としては誤り。

cosmoscanの以下の箇所を、
https://github.com/lcnem/cosmoscan/blob/163a727d0976bd9e4a63c2ad9682a29b69046d4c/projects/cosmoscan/src/model/cosmos/bank.service.ts#L28

cosmos-client-tsのテストコードの以下のように書き換えれば解決では　とのこと。
https://github.com/cosmos-client/cosmos-client-ts/blob/72473c2dfb6d94853e99012806c398ed616d79aa/src/rest/cosmos/bank/bank.spec.ts#L26

**Comment by YasunoriMATSUOKA** [comment]
https://github.com/lcnem/cosmoscan/compare/58ad579d9e06%5E...b2acc566af8b
上記修正で、ng serve時点でのエラーは解決し、画面が表示されるようになりました。

動作確認のため、以前デバッグ用に教えていただいたmnemonicでkeyをcreateして、bank -> Send coins -> フォームに適当な値を入力して、txアナウンスを試みたのですが、以下の行でエラーが発生しているようでした。ただ、特にエラー内容等は表示されていない状況です。

https://github.com/lcnem/cosmoscan/blob/b2acc566af8b254295f425a2385822a219dbc6d7/projects/cosmoscan/src/model/cosmos/bank.service.ts#L58

エラー発生時の画面のスクショを以下に添付します。

![image](https://user-images.githubusercontent.com/55148923/125014917-7f9ca800-e0a9-11eb-9448-4ac6f407d567.png)

エラー解決のための次に注目すべき箇所等あるでしょうか？
お手数ですが、アドバイス頂けると助かります。よろしくお願いします。

**Comment by KimuraYu45z** [comment]
エラーではなく警告のことでしょうか？

**Comment by YasunoriMATSUOKA** [comment]
すみません、スクショにとれていなかった＆コメントにかけていなかった状況ですが、sendボタンを押しても、画面が送信後の状態に遷移せず、Error has occuredのようなスナックバーが表示された状態になりました。consoleには特にそれらしいエラーは表示されていなかったという状況でした。

**Comment by KimuraYu45z** [comment]
projects/cosmoscan/src/model/cosmos/bank.application.service.ts
のtryに引っかかってるという話なんで、キャッチしたエラーをconsole.errorで出すとかどうでしょうか。

**Comment by YasunoriMATSUOKA** [comment]
ありがとうございます。試してみます。

**Comment by KimuraYu45z** [comment]
instance ofがなんらかの原因で突破できてないという可能性もありますね。
instance ofの一行前に、console.log(account)もお願いします。

**Comment by YasunoriMATSUOKA** [comment]
承知しました！

**Comment by YasunoriMATSUOKA** [comment]
試してみたところ、以下のような結果になりました。

accountのconsole

```
e {address: "jpyx10lcj22kzftvnduchatmnsnhfljeky5ghd398wt", pub_key: e, account_number: 0, sequence: 2}
account_number: 0
address: "jpyx10lcj22kzftvnduchatmnsnhfljeky5ghd398wt"
pub_key: e {}
sequence: 2
__proto__: Object
```

エラー内容

```
TypeError: e.isZero is not a function
    at W.signDoc (main.js:1)
    at W.signDocBytes (main.js:1)
    at t.<anonymous> (907.js:1)
    at Generator.next (<anonymous>)
    at s (main.js:1)
    at l.invoke (polyfills.js:1)
    at Object.onInvoke (main.js:1)
    at l.invoke (polyfills.js:1)
    at t.run (polyfills.js:1)
    at polyfills.js:1
```

スクショ

![image](https://user-images.githubusercontent.com/55148923/125016314-1a968180-e0ac-11eb-90e8-30f2a89f4534.png)

**Comment by YasunoriMATSUOKA** [comment]
isZeroがうまく機能していない？

**Comment by KimuraYu45z** [comment]
longではなくnumberが入っちゃってる、とかじゃないですかね。

**Comment by KimuraYu45z** [comment]
あと、accountは本当にBaseAccountのインスタンスになっているのかあやしくないですか？オブジェクトになっちゃってたりしてないですかね。

**Comment by YasunoriMATSUOKA** [comment]
> あと、accountは本当にBaseAccountのインスタンスになっているのかあやしくないですか？オブジェクトになっちゃってたりしてないですかね。

これを確認するには、以下の箇所で落ちずに、以降が実行されているかどうかを確認すればよいという理解であっているでしょうか？
https://github.com/lcnem/cosmoscan/blob/b2acc566af8b254295f425a2385822a219dbc6d7/projects/cosmoscan/src/model/cosmos/bank.service.ts#L25

**Comment by KimuraYu45z** [comment]
その一行前でconsole.log(account)があれば確認できるはずです。

**Comment by YasunoriMATSUOKA** [comment]
accountのもとのデータ

```
{"data":{"account":{"@type":"/cosmos.auth.v1beta1.BaseAccount","address":"jpyx10lcj22kzftvnduchatmnsnhfljeky5ghd398wt","pub_key":{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"AvSf2U/B23UZKvLTD0E4xqJ33Nn0Z552nXCkkwEfleiu"},"account_number":"0","sequence":"2"}},"status":200,"statusText":"OK","headers":{"content-length":"314","content-type":"application/json"},"config":{"url":"http://a.test.jpyx.lcnem.net:1317/cosmos/auth/v1beta1/accounts/jpyx10lcj22kzftvnduchatmnsnhfljeky5ghd398wt","method":"get","headers":{"Accept":"application/json, text/plain, */*"},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1},"request":{"__zone_symbol__xhrSync":false,"__zone_symbol__xhrURL":"http://a.test.jpyx.lcnem.net:1317/cosmos/auth/v1beta1/accounts/jpyx10lcj22kzftvnduchatmnsnhfljeky5ghd398wt","__zone_symbol__readystatechangefalse":[{"type":"eventTask","state":"scheduled","source":"XMLHttpRequest.addEventListener:readystatechange","zone":"angular","runCount":6}],"__zone_symbol__abortfalse":[{"type":"eventTask","state":"scheduled","source":"XMLHttpRequest.addEventListener:abort","zone":"angular","runCount":0}],"__zone_symbol__errorfalse":[{"type":"eventTask","state":"scheduled","source":"XMLHttpRequest.addEventListener:error","zone":"angular","runCount":0}],"__zone_symbol__timeoutfalse":[{"type":"eventTask","state":"scheduled","source":"XMLHttpRequest.addEventListener:timeout","zone":"angular","runCount":0}],"__zone_symbol__xhrScheduled":true,"__zone_symbol__xhrErrorBeforeScheduled":false,"__zone_symbol__xhrTask":{"type":"macroTask","state":"notScheduled","source":"XMLHttpRequest.send","zone":"angular","runCount":0}}}
```

**Comment by YasunoriMATSUOKA** [comment]
デバッグで使っているconfig.jsです

```json
const config = {
  restURL: `http://a.test.jpyx.lcnem.net:1317`,
  websocketURL: `ws://a.test.jpyx.lcnem.net:26657`,
  chainID: 'jpyx-1-test',
  bech32Prefix: {
    accAddr: 'jpyx',
    accPub: 'jpyxpub',
    valAddr: 'jpyxvaloper',
    valPub: 'jpyxvaloperpub',
    consAddr: 'jpyxvalcons',
    consPub: 'jpyxvalconspub',
  },
  extension: {
    navigations: [
      {
        name: 'JPYX',
        link: '/jpyx',
      }
    ],
    messageActions: ['']
  }
};

```

**Comment by KimuraYu45z** [comment]
自動生成コード

```
BaseAccount.prototype.account_number = $util.Long ? $util.Long.fromBits(0,0,true) : 0;
```

この$util.LongがnullだとLong型の代わりにnumberが使われてる。
ということはやっぱりLongをうまくリンクできていない。

**Comment by KimuraYu45z** [comment]
https://github.com/protobufjs/protobuf.js/issues/921
見つけた。

polyfill的なことをしないとLongがやっぱりbundleされないんですね。

ちなみに以下のコミットで解決
https://github.com/cosmos-client/cosmos-client-ts/commit/0aaacc2a35f168a18c8d9ba8dcf0faf3a91a2b86

**Comment by YasunoriMATSUOKA** [comment]
ありがとうございます！
cosmos-client-tsのバージョンを上記修正済のv0.42.7にして再度試してみます。

**Comment by YasunoriMATSUOKA** [comment]
@KimuraYu45z @Senna46 
トランザクション送信に成功しました！デバッグ助けていただきありがとうございました！
![image](https://user-images.githubusercontent.com/55148923/125022752-59cacf80-e0b8-11eb-9217-e4c1815bb211.png)
