### ISSUE TITLE
[優先度高]残高をわかりやすく表示する機能の実装

### ISSUE THREAD

**Issue by YasunoriMATSUOKA** [lcnem/cosmoscan#64]
2021/07/09打ち合わせで出た話です。詳細は検討が必要と思いますが、一旦Issue化しておきます。

**Comment by YasunoriMATSUOKA** [comment]
素案1

http://a.test.jpyx.lcnem.net/cosmos/bank 画面で、Send coinsと同様にナビゲーションリストとして、Show balancesを追加し、それをクリックすると、Send coinsと同様にアカウント選択のモーダルが表示され、モーダルでアカウント選択すると、残高表示の画面が表示されるようにする

**Comment by YasunoriMATSUOKA** [comment]
素案2

http://a.test.jpyx.lcnem.net/keys 画面からアカウント選択して遷移される画面 http://a.test.jpyx.lcnem.net/keys/{id} に、残高表示を追加する。表示内容は http://a.test.jpyx.lcnem.net/accounts/{address} と同様のものを末尾に追加すれば良いと思う。

**Comment by YasunoriMATSUOKA** [comment]
素案3

http://a.test.jpyx.lcnem.net/cosmos/bank 画面で、ユーザーがkeyをcreateした全アカウントの残高表示を追加する。
Functionsの上にBalancesとして、id, そのidに対応したアドレスの残高の表示( http://a.test.jpyx.lcnem.net/account/{address} ) を列挙するイメージ。

**Comment by KimuraYu45z** [comment]
論理的な一貫性としては素案1のほうが適している気がします。
素案2でもなく、トップページに残高表示するような場合(ただしkey選択が必要なので実装は難しすぎる)だと、ユーザーにとっても直感的ですが、keys/{id}での表示だとユーザーにとって直感的になるわけでもなく、論理的な一貫性も失われるので、素案1がいいんじゃないかなと！

素案3は、(functionsはなにかの間違いですかね？)通信量が大きくなるので読み込みも遅くなりますし、避けたほうが良いような感じもあります。

**Comment by YasunoriMATSUOKA** [comment]
コメントありがとうございます！
素案1が論理的な一貫性があるという点、同意です。
素案1のイメージで進める方向で、大村さんに作業を依頼させていただき、木村さんからサポートしてもらう形でお願いしても良いでしょうか？
お手数ですがよろしくお願いします。

素案3では、以下のような形で画面に追加するイメージを持っていましたが、ご指摘の通り、必要なデータが多くなり、遅くなると思うので、避けた方が良いという意見に同意です。

画面内の項目

Balances

id_1
id_1の残高表示の表

id_2
id_2の残高表示の表

...(以下、登録されている全keyを表示)

Functions

Send coins

**Comment by KimuraYu45z** [comment]
>大村さんに作業を依頼させていただき、木村さんからサポートしてもらう形でお願いしても良いでしょうか？

はい。 @Senna46 にはそろそろ自走の練習もしてもらわなきゃいけないので、それ考えつつサポート入っておきます。

**Comment by YasunoriMATSUOKA** [comment]
ウォレットという観点からUI, UXを捉えると、個人的な意見としては、以下の要素が一画面にまとまっていると、ユーザー目線からはわかりやすいと感じています。(その分、重くなってしまうかもですが...)

アカウント選択 ... プルダウンなどで登録済みのidから選べるとわかりやすい？プルダウン末尾にはkey createへのリンクを設定しておくなど？
アカウント情報表示
残高表示
直近のトランザクション履歴(5〜10件くらいに絞る) ... クリックしたら全件表示画面へ遷移
直近のステーキング履歴(5〜10件くらいに絞る) ... クリックしたら全件表示画面へ遷移
各種機能へのリンクのボタン ... サイドナビでも良いかも(key create, send coins, signなど)

**Comment by KimuraYu45z** [comment]
結論
accounts/{{address}}に飛ばす方法を考える

**Comment by KimuraYu45z** [comment]
うまいことkey選んでそのkeyのaddressをとる(これは秒)、んでaccounts/{{address}}に飛ばす

**Comment by KimuraYu45z** [comment]
結論

accounts/{{address}}

にすべてのGET系情報を集約する。

**Comment by KimuraYu45z** [comment]
一応done扱い
PRだけたのみます
