### ISSUE TITLE
[優先度最高]アーニングスをわかりやすく表示する機能の実装

### ISSUE THREAD

**Issue by YasunoriMATSUOKA** [lcnem/cosmoscan#65]
2021/07/09打ち合わせで出た話です。詳細は検討が必要と思いますが、一旦Issue化しておきます。

**Comment by YasunoriMATSUOKA** [comment]
Issue化した後に思ったのですが、これはbotanyの側で実装すべき機能でしょうか？

**Comment by KimuraYu45z** [comment]
stakingモジュールの機能で実装できるならこちらでいいです！

**Comment by YasunoriMATSUOKA** [comment]
ありがとうございます！

**Comment by YasunoriMATSUOKA** [comment]
素案1

validator向け収益情報表示画面として既存の以下URLに項目を追加して表示する
http://a.test.jpyx.lcnem.net/cosmos/staking/validators/{address}
(メモ: URL直接入力した場合は機能するが、直前のアカウント選択画面の http://a.test.jpyx.lcnem.net/cosmos/staking/validators の対象アカウントをクリックした際の画面遷移はエラーになっている。おそらくroutingの設定でシンプルにパスが間違っているだけと思う。)

delegator向け収益情報表示画面として(現時点では未実装の)以下URLに項目を追加して表示する
http://a.test.jpyx.lcnem.net/cosmos/staking/delegators/{address}

**Comment by YasunoriMATSUOKA** [comment]
素案2

素案1とは別のページに情報を表示する。例えば以下など？
validator
http://a.test.jpyx.lcnem.net/cosmos/staking/validators/{address}/earnings

delegator
http://a.test.jpyx.lcnem.net/cosmos/staking/delegators/{address}/earnings

**Comment by YasunoriMATSUOKA** [comment]
@Senna46 以下の点、現時点では自分自身の理解が曖昧ですが、一旦ここまでメモ残した状態で、タスクふらせてもらいます。

@KimuraYu45z お手数ですが、サポートお願いしますm(__)m

具体的な表示項目としては、報酬発生時の以下情報をテーブルとして一覧表示するといったイメージ？

- ブロック高さ
- 日時
- 報酬額(トークンそのものの数量とDenomのみ表示)

他にもこれまでの報酬総額や利率などの情報が求められる可能性もある？

**Comment by KimuraYu45z** [comment]
@Senna46 cosmos client tsのソースコードのうち、staking関連のものの中から探せば使える機能が見つかるはずです

**Comment by KimuraYu45z** [comment]
routingとしてはaccounts/{{address}}でいいんでしょうけど、コンポーネントはcosmos moduleごとに(bankとかstakingとか)分割したほうがコードの見通しはよくなるかも。
angularのpage componentでもpresentation componentでもなくcontainer component使う感じで。

**Comment by YasunoriMATSUOKA** [comment]
container component化したほうが今後便利そうなものとして、とりあえず、各アカウントに紐づく情報として、以下を挙げてみました。これらのcontainer componentを作り、それをアカウント情報表示ページ( accounts/{{address}} )に追加していくという流れでイメージあっているでしょうか？

- [ ] 公開可能なアカウント情報の表示 ... アドレス、公開鍵等の情報の表示
- [ ] 残高表示
- [ ] トランザクション履歴表示
- [ ] バリデーター報酬履歴表示 ... バリデーター報酬という言葉は何か変な言葉かもしれませんがいわんとすることは伝わるでしょうか。
- [ ] デリゲーター報酬履歴表示 ... デリゲーター報酬以下略

**Comment by Senna46** [comment]
Staking関連のソースコードを探してみたのですが、cosmos-cliant-tsのsrc/rest/staking/module.tsを参考に、という感じでしょうか？
spec.tsと聞いた気がするのですが、見つからないです。

**Comment by YasunoriMATSUOKA** [comment]
すみません、こちらで確認前に、bankだとspec.ts(=テスト)が書かれていたから、他もあるんじゃないか...くらいのイメージでコメントしてしまった感じでした。
確かに、stakingの中にはspec.tsはなかったので、cosmos-client-tsの使い方としては、cosmoscanの中のコードを呼び出し方的に参考にしつつ、ご認識の通り、cosmos-client-ts内の、src/rest/staking/module.tsも参考にしつつ実装検討頂くというイメージかと思います。

**Comment by KimuraYu45z** [comment]
調査系は優先順位低でこれ優先順位最高でお願いします

**Comment by YasunoriMATSUOKA** [comment]
画面表示内容イメージ図素案

![image](https://user-images.githubusercontent.com/55148923/125577209-39d8bed3-2ef7-493a-9bcb-f2c6ebd33ad1.png)

**Comment by KimuraYu45z** [comment]
@Senna46 
presentation component…cosmoscanでいうviewフォルダ内にあるcomponentのこと。ロジックの責任はもたず表示の責任だけ持ってる。
page component…cosmoscanでいうappフォルダ内にあるcomponentのこと。routingに紐づけされる。ロジックの責任も持っていて、presentation componentに値を渡す責任をもつ。

container component…cosmoscanにはまだない。routingに紐づけはされないが、page component内で表示される。ロジックの責任を持っていて、presentation componentに値を渡す責任をもつ。

**Comment by Senna46** [comment]
`projects/cosmoscan/src/app/accounts/account/account.component.ts`
```
    this.account$ = combined$.pipe(
      mergeMap(([sdk, address]) =>
        rest.cosmos.auth
          .account(sdk.rest, address)
          .then((res) => {
            console.log(res);
            return res.data && cosmosclient.codec.unpackAny(res.data);
          })
          .catch((_) => {
            console.log(_);
            return undefined;
          }),
      ),
    );
```
ファイル32行目`unpackAny`が動作していないと思われる不具合で、`Account info`が表示されない。
```
ERROR TypeError: Cannot read property 'length' of undefined
    at new S (main.js:1)
    at new A (main.js:1)
    at s.project (757.js:1)
    at s._next (main.js:1)
    at s.next (main.js:1)
    at s._next (main.js:1)
    at s.next (main.js:1)
    at s._next (main.js:1)
    at s.next (main.js:1)
    at i._subscribe (main.js:1)
Oo @ main.js:1
```

また、`staking-earning-info`ブレンチでValidator Earningを取って表示する機能を追加したが、結果を取れていない。
Acckeyは正常に取れているようなので、その後の処理に問題あり。
エラーログは現状確認できていません。

Delegator Earningは本件解決後、同様に実装予定。

**Comment by YasunoriMATSUOKA** [comment]
staking.component.tsで、以下の行でエラーが出ているように思いました。

https://github.com/lcnem/cosmoscan/blob/bfeade1440cfab98dfeec329b3221a334e4e823d/projects/cosmoscan/src/app/accounts/account/staking/staking.component.ts#L28

**Comment by KimuraYu45z** [comment]
https://github.com/cosmos-client/cosmos-client-ts/commit/b6c913e672eed4c7307efc1df2b9e216cc6aac98

この変更(v0.42.9)によりBaseVestingAccountのUnpackが可能になったと思います。
BaseAccountのinstance ofにはtrueになってくれないことに注意。

**Comment by YasunoriMATSUOKA** [comment]
unpackAnyのエラー、0.42.9でも未解決

直前のレスポンスをJSON.stringifyした結果
```
{"data":{"account":{"@type":"/cosmos.auth.v1beta1.BaseAccount","address":"jpyx10lcj22kzftvnduchatmnsnhfljeky5ghd398wt","pub_key":{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"AvSf2U/B23UZKvLTD0E4xqJ33Nn0Z552nXCkkwEfleiu"},"account_number":"0","sequence":"13"}},"status":200,"statusText":"OK","headers":{"content-length":"315","content-type":"application/json"},"config":{"url":"http://a.test.jpyx.lcnem.net:1317/cosmos/auth/v1beta1/accounts/jpyx10lcj22kzftvnduchatmnsnhfljeky5ghd398wt","method":"get","headers":{"Accept":"application/json, text/plain, */*"},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1},"request":{"__zone_symbol__xhrSync":false,"__zone_symbol__xhrURL":"http://a.test.jpyx.lcnem.net:1317/cosmos/auth/v1beta1/accounts/jpyx10lcj22kzftvnduchatmnsnhfljeky5ghd398wt","__zone_symbol__readystatechangefalse":[{"type":"eventTask","state":"scheduled","source":"XMLHttpRequest.addEventListener:readystatechange","zone":"angular","runCount":6}],"__zone_symbol__abortfalse":[{"type":"eventTask","state":"scheduled","source":"XMLHttpRequest.addEventListener:abort","zone":"angular","runCount":0}],"__zone_symbol__errorfalse":[{"type":"eventTask","state":"scheduled","source":"XMLHttpRequest.addEventListener:error","zone":"angular","runCount":0}],"__zone_symbol__timeoutfalse":[{"type":"eventTask","state":"scheduled","source":"XMLHttpRequest.addEventListener:timeout","zone":"angular","runCount":0}],"__zone_symbol__xhrScheduled":true,"__zone_symbol__xhrErrorBeforeScheduled":false,"__zone_symbol__xhrTask":{"type":"macroTask","state":"notScheduled","source":"XMLHttpRequest.send","zone":"angular","runCount":0}}}
```

発生していたエラー
```
Error: This type is not registered
    at Module.B (main.js:1)
    at 757.js:1
    at l.invoke (polyfills.js:1)
    at Object.onInvoke (main.js:1)
    at l.invoke (polyfills.js:1)
    at t.run (polyfills.js:1)
    at polyfills.js:1
    at l.invokeTask (polyfills.js:1)
    at Object.onInvokeTask (main.js:1)
    at l.invokeTask (polyfills.js:1)
```

**Comment by KimuraYu45z** [comment]
ぬぬぬぬうう？？
てっきり@typeにはBaseVestingAccountが入っているものだと思っていました。(0.42.9の変更もそれ目的)
BaseAccountが登録されていないのは、かなり不可解ですね。

**Comment by YasunoriMATSUOKA** [comment]
全然違うconsoleを間違えて抜き出して書いているかもしれないので、念のため確認します。

**Comment by YasunoriMATSUOKA** [comment]
間違いありませんでした。
![image](https://user-images.githubusercontent.com/55148923/125880336-07b0ba31-6f37-406d-9bb0-1f5d0c26ded7.png)

**Comment by YasunoriMATSUOKA** [comment]
現状整理

以下コメントの問題は解決
https://github.com/lcnem/cosmoscan/issues/65#issuecomment-880573891

以下コメントの問題は未解決
https://github.com/lcnem/cosmoscan/issues/65#issuecomment-881114411

**Comment by KimuraYu45z** [comment]
1つ目ありがとうございます！

**Comment by KimuraYu45z** [comment]
https://github.com/cosmos-client/cosmos-client-ts/search?q=This+type+is+not+registered&type=

**Comment by YasunoriMATSUOKA** [comment]
ちょっと行儀悪いですが、node_modulesの以下のファイル中にconsole書いて、unpackAnyの実装箇所で何の値が入っているか、確認してみたところ、typeURLがundefinedになってしまっているようでした。

node_modules\cosmos-client\esm\types\codec\module.js

```
export function unpackAny(value) {
    console.log(value);
    const typeURL = value && value['@type'];
    console.log(typeURL);
    console.log(config.codecMaps.fromObject[typeURL]);
    if (!typeURL || !config.codecMaps.fromObject[typeURL]) {
        throw Error('This type is not registered');
    }
    return config.codecMaps.fromObject[typeURL](value);
}

console.log(value)の箇所

```
{"account":{"@type":"/cosmos.auth.v1beta1.BaseAccount","address":"jpyx10lcj22kzftvnduchatmnsnhfljeky5ghd398wt","pub_key":{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"AvSf2U/B23UZKvLTD0E4xqJ33Nn0Z552nXCkkwEfleiu"},"account_number":"0","sequence":"13"}}
```

console.log(typeURL)の箇所

```
undefined
```

console.log(config.codecMaps.fromObject[typeURL])の箇所

```
undefined
```

![image](https://user-images.githubusercontent.com/55148923/125882207-6ac630d0-b9eb-45d3-a6a8-57b580666055.png)

**Comment by KimuraYu45z** [comment]
あー、unpackAnyにはdataじゃなくてdata.account入れれば解決する話じゃないですかね？

**Comment by YasunoriMATSUOKA** [comment]
publicKeyの表示で問題があり、一旦、publicKeyの表示をコメントアウトした状態で、テストネットa, b, c, dにデプロイした状態です。

publicKeyの問題は以下の通り

概要
https://github.com/lcnem/cosmoscan/issues/65#issuecomment-881114411

スクショ
https://github.com/lcnem/cosmoscan/issues/65#issuecomment-881121736

木村さんにて現時点で調査いただいた中で分かったことなどのメモ

logのJSONみてると `"pub_key":{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"AvSf2U/B23UZKvLTD0E4xqJ33Nn0Z552nXCkkwEfleiu"}` が入ってるので、unpackがうまくできていないなどの可能性が考えられる。

詳細

BaseAccount.pub_keyはIAny型で、これは

```
{
  type_url: string
  value: string // protobufバイナリのUint8ArrayをBase64化
}
```

というもので、

```
{
  '@type': string
  ...value
}
```

とまた別物(これはcosmos独自表現と思えば良い)なので、後者で返ってくるresponseのフォーマットを前者にそろえなければならない

結論：後者フォーマットのresponseをいったんすべて再帰的にprotobufエンコードしてやることでIAny型と整合的にする。

**Comment by YasunoriMATSUOKA** [comment]
@Senna46 
https://github.com/lcnem/cosmoscan/issues/65#issuecomment-881232872 の問題点は、木村さんにて https://github.com/cosmos-client/cosmos-client-ts/releases/tag/v0.42.11 の修正を加えて頂き、publicKeyを表示できるようになったと思います。

どこかのタイミングで、コメントアウトしたpublicKeyの表示箇所を再度有効化してうまくいくか試してみて頂けると助かります。

よろしくお願いします。

**Comment by Senna46** [comment]
@YasunoriMATSUOKA cosmos-client-tsの修正を反映して、表示ができました。
PR作成してます。

**Comment by YasunoriMATSUOKA** [comment]
@Senna46 cc: @KimuraYu45z 
大村さん、先ほどプルリク頂き、松岡にてレビュー承認した件、問題があったようです。
以下の木村さんのコメントを確認の上、修正をお願いします。
https://github.com/lcnem/cosmoscan/pull/73#issuecomment-882271484
https://github.com/lcnem/cosmoscan/pull/73#issuecomment-882274224

**Comment by KimuraYu45z** [comment]
@Senna46 終わったissueはこまめに消すようたのみますー
