### ISSUE TITLE
[優先度低]keyをcreateせずにbankのsend coinsをクリックするとマウス操作ではキー選択モーダルとメッセージダイアログ表示の無限ループ状態になってしまう

### ISSUE THREAD

**Issue by YasunoriMATSUOKA** [lcnem/cosmoscan#68]
ホーム画面等の別のURLを指定すれば復帰できるのですが、一般的なユーザーが行うであろうマウス操作ではキー選択モーダルとメッセージダイアログの間を行き来するループから抜けられないと感じてしまうように思い、どこかで修正できるとよいと思いました。

![issue_20210710_loop_on_bank_send_without_key](https://user-images.githubusercontent.com/55148923/125139050-c68eaa00-e14a-11eb-98c4-cd9e449eb7d2.gif)

**Comment by KimuraYu45z** [comment]
@Senna46 key-select-dialog (ctrl pで検索かければいい)のなかに、keys(key一覧ページのこと)へのrouterLink(わからなければググる)をはれば解決かと思われる

**Comment by Senna46** [comment]
`key-select-dialog.component.html`に以下、追記したところ、キーがある状態だと追記部分も表示されるのですが、キーなしで`Send Coin`しようとすると空のdialogがループする問題が解決しておりません。

```
    <mat-list-item routerLink="/keys">
      <mat-icon color="accent">list </mat-icon>
      Key List
    </mat-list-item>
```

**Comment by KimuraYu45z** [comment]
どっかのブランチにpushしてみてー
