### ISSUE TITLE
[優先度中]cosmos-client-tsバージョンアップによる変更対応

### ISSUE THREAD

**Issue by YasunoriMATSUOKA** [lcnem/cosmoscan#75]
@Senna46 

以下、木村さんのメモ

変更点は以下です。
https://github.com/cosmos-client/cosmos-client-ts/commit/59f62a3230b67013da615ea9626a6ef1e960c1ac
cosmoscanで変えないといけないとこ
cosmosclient.secp256k1→proto.cosmos.crypto.secp256k1
そのたcosmos.authとかのproto型定義使ってるとこはすべてproto.cosmos.authみたいにprotoからはじめる

**Comment by Senna46** [comment]
概ね変更できたのですが、`ng serve`の際に以下のエラーがでます。
```
./projects/cosmoscan/src/view/accounts/account/account.component.ts:2:0-49 - Error: Module not found: Error: Package path ./cjs/proto is not exported from package /home/user/src/github.com/lcnem/cosmoscan/node_modules/cosmos-client (see exports field in /home/user/src/github.com/lcnem/cosmoscan/node_modules/cosmos-client/package.json)
```

`cosmos.base.v1beta1.ICoin`に対して、
`import { cosmos } from 'cosmos-client/cjs/proto';`
でインポートしているのでここが間違えている可能性が高いですが、cosmos-client-tsを見ても、`cosmos-client/cjs/proto`が正しい気がするのですが、どこが問題かわかりますでしょうか？

**Comment by KimuraYu45z** [comment]
そこも{proto}from 'cosmos-client'
に変えてほしいです

**Comment by Senna46** [comment]
変更点になかったように見えましたが、`cosmos.base.v1beta1.ICoin`も`proto.cosmos.base.v1beta1.ICoin`に変えて大丈夫ですか？

**Comment by KimuraYu45z** [comment]
それは変更点に含まれるものとして察してほしかった省略箇所でした。

**Comment by Senna46** [comment]
cosmos-client-tsのコードを見ても`proto.cosmos.base.v1beta1.ICoin`の記載がないので、ここは変更なしで別で`cosmos`をインポートするのかと思ってました。
変更と動作確認できたのでPR送ります。

**Comment by KimuraYu45z** [comment]
cosmos-client-tsの変更点的としても、import、exportの構造の変化はcosmos.baseも影響を受けています。
