### ISSUE TITLE
[優先度中]delegatorの報酬に関する情報を表示する

### ISSUE THREAD

**Issue by YasunoriMATSUOKA** [lcnem/cosmoscan#77]
@Senna46 
以下URLのような、accounts/{{accAddress}} の画面に、Validatorの報酬に関する情報と同様に、Delegatorの報酬に関する情報を表示する。
http://a.test.jpyx.lcnem.net/accounts/jpyx10lcj22kzftvnduchatmnsnhfljeky5ghd398wt

@KimuraYu45z 
違和感あればフォロー頂けると助かります。

**Comment by Senna46** [comment]
今、バリデーターをStakingに入れているのでそれを他のコンテナ（Validator？）に移してから、空いたStakingにDeligator eaningを書いていくという方針で問題ないですか？

**Comment by KimuraYu45z** [comment]
いえバリデータ報酬を取得するAPIはcosmos sdkのvestingモジュールにあるのでvestingコンテナが理想ですね。
delegatorモジュールやvalidatorモジュールは存在しません。
