### ISSUE TITLE
[優先度高]etherscan参考に、latest block

### ISSUE THREAD

**Issue by KimuraYu45z** [lcnem/cosmoscan#78]
コンテナcomponent（blocksとかの名前でよい）作って、トップページに表示が良いと思われる
https://etherscan.io/

**Comment by KimuraYu45z** [comment]
homeの中にblocks componentコンテナつくる

**Comment by Senna46** [comment]
![latestblock](https://user-images.githubusercontent.com/29295263/127462418-67b1a27c-24a2-42fd-bc5c-3e2236fbd689.PNG)

projects/cosmoscan/src/app/home/block/block.component.ts
```
this.cosmosSDK.websocketURL$.pipe(first()).subscribe((websocketURL) => {
      const ws = websocket.connect(websocketURL);
      ws.next({
        id: '1',
        jsonrpc: '2.0',
        method: 'subscribe',
        params: ["tm.event = 'NewBlock'"],
      });
      this.latestBlocks$ = ws.asObservable();
```
の最後の1行を
```
const wsObservable = ws.asObservable();
this.latestBlocks$ = wsObservable.scan((currentValue) => [currentValue], []);
```
に変更して配列にしようと思ったのですが、'scan' は型 'Observable<RequestSchema | ResponseSchema>' に存在しないというエラーが出ます。
ws.asObservable()の'Observable<RequestSchema | ResponseSchema>' でscanを使うにはどのようにすればいいのでしょうか？

**Comment by KimuraYu45z** [comment]
https://www.learnrxjs.io/learn-rxjs/operators/transformation/scan
送ったリンクを真似してください

**Comment by Senna46** [comment]
以下のように修正することで値は取れたかと思います。(配列を20に抑えるのは未実装)
```
      const ws = websocket.connect(websocketURL);
      ws.next({
        id: '1',
        jsonrpc: '2.0',
        method: 'subscribe',
        params: ["tm.event = 'NewBlock'"],
      });
      this.latestBlocks$ = ws.asObservable().pipe(scan<any>((all, current) => [...all, current], []));
```

![image](https://user-images.githubusercontent.com/29295263/127612861-ffce8ba2-378a-4d09-b14a-550dbc57b323.png)

あとはngForで配列の要素を表示するだけなのですが、以下のものではエラーが出ました。
```
<h2>Latest Blocks</h2>

<mat-card>
  <mat-nav-list *ngFor="let block of latestBlocks?.result.data.value.block.header">
    <mat-list-item>
      <span class="column-value">{{ block.height }}</span>
      <span fxFlex="auto"></span>
      <span class="column-value">{{ block.time }}</span>
    </mat-list-item>
    <mat-divider></mat-divider>
  </mat-nav-list>
</mat-card>
```
ngForの使い方にまだ自信はないのですが、どこが問題でしょうか？
アドバイスいただけますと幸いです。

**Comment by KimuraYu45z** [comment]
cannot read property x of undefined
これでググってみてください。 latestBlocks?.resultがundefinedです

**Comment by KimuraYu45z** [comment]
エラー内容でググる「cannot read property x of undefined」ことと

https://www.google.com/search?q=ng+for

不安な内容があったらググってなにかと比較してみることを徹底しましょう

**Comment by KimuraYu45z** [comment]
そのコードを見る限りではオブジェクトフィールドアクセス演算子「.」とof演算子の優先順位を把握できていないのと、 配列そのものと配列要素の区別の理解が曖昧かなという気がします
ng forでなくてもtypescriptでのfor(const x of xs)と同じ話ですしそっちで考えたほうがはやいかもしれませんが

**Comment by Senna46** [comment]
```
<h2>Latest Blocks</h2>
<mat-card>
  <mat-nav-list>
    <ng-container *ngFor="let block of latestBlocks">
      <mat-list-item>
        <span class="column-value">{{ block.result.block.data.value.block.headerblock.height }}</span>
        <span fxFlex="auto"></span>
        <span class="column-value">{{ block.result.data.value.block.headerblock.time }}</span>
      </mat-list-item>
      <mat-divider></mat-divider>
    </ng-container>
  </mat-nav-list>
</mat-card>
```
このように修正するというのがわかりましたが、`Type 'ResponseSchema | null | undefined' is not assignable to type 'NgIterable<any> | null | undefined'.`エラーでngForが使えていません。

latestBlockの中身はjsonrpc、id、resultのプロパティを持つ配列要素が配列として入っているという認識ですが、これは合っていますでしょうか？
その場合、latestBlockの型はwebsocket.ResponseSchemaから変えないといけないということでしょうか？

**Comment by KimuraYu45z** [comment]
ngforにいれられるのは`ResponseSchema[] | null | undefined`

**Comment by Senna46** [comment]
ありがとうございます。表示のやり方はわかりました。
あと、`Cannot read property 'value' of undefined`エラーを解決すれば表示できそうなのでもう少しやってみます。

**Comment by Senna46** [comment]
メモ：最初に取れるデータが
```
 { jsonrpc: '2.0', id: '1', result: {} }
````
のため、`value`でundefinedエラーが発生
