### ISSUE TITLE
[優先度低]cdpの報酬に関する情報を表示する

### ISSUE THREAD

**Issue by YasunoriMATSUOKA** [lcnem/cosmoscan#79]
@Senna46 
以下URLのような、accounts/{{accAddress}} の画面に、CDPの報酬(=validator, delegatorとしての報酬とは全く別もの。cdpモジュールの管轄。)に関する情報を表示する。
http://a.test.jpyx.lcnem.net/accounts/jpyx10lcj22kzftvnduchatmnsnhfljeky5ghd398wt

@KimuraYu45z
違和感あればフォロー頂けると助かります。

**Comment by KimuraYu45z** [comment]
cdpはcosmos sdkの機能ではなくbotany特有の機能なので、cosmoscanに実装するのはまずいですね。botany/cosmoscan-extensionに表示すればいいと思います。

**Comment by YasunoriMATSUOKA** [comment]
失礼しました。botany側に移しておきます。
