### ISSUE TITLE
etherscan参考に、latest txs

### ISSUE THREAD

**Issue by YasunoriMATSUOKA** [lcnem/cosmoscan#81]
@Senna46 
コンテナcomponent（txsとかの名前）作って、トップページに表示が良い？
https://etherscan.io/

@KimuraYu45z 
latest block同様にlatest txsも必要かと思い書いてみました。違和感あればフォロー頂けると助かります。

**Comment by KimuraYu45z** [comment]
被っちゃいましたｗ　（予測ができているのは良いことです！）
https://github.com/lcnem/cosmoscan/issues/80

**Comment by YasunoriMATSUOKA** [comment]
こっち消しておきますm(__)m
